### ISSUE TITLE
Most of the panels show "No Data"

### ISSUE THREAD

**Issue by accelide** [couchbaselabs/cbprometheus_python#56]
Most of the panels in the shows "No Data". Is there any additional configuration that need to be done?

Below is the screenshot of "Couchbase Performance Dashboard". And "XDCR" Dashboard has also has panels with "No Data". For all the "No Data" panels, PromQL metrics are not found in Prometheus.

<img width="2407" alt="image" src="https://user-images.githubusercontent.com/12295380/79802279-a7c9ab00-832d-11ea-9a00-ce394d3600d6.png">

**Comment by bentonam** [comment]
@accelide  was a cluster selected from the dropdown?  For one of those panels, if you choose Edit and copy the PromQL statement and execute it in Prometheus do you get results?   You will need to change it slightly as the variables will not work in Prometheus

**Comment by accelide** [comment]
I have selected cluster from drop down. Attached are screenshots.

![Xnip2020-04-21_12-00-12](https://user-images.githubusercontent.com/12295380/79886943-ee6be380-83c7-11ea-98f5-16f9f6e1bd8b.jpg)
![Xnip2020-04-21_12-01-11](https://user-images.githubusercontent.com/12295380/79886952-f166d400-83c7-11ea-8557-e9aae88b32ba.jpg)

**Comment by accelide** [comment]
Thanks Aaron for helping with the "No Data" panels. 

can you include pulling "/nodes/self" metrics to get filesystem/storage related information.

"curl -X GET -u <administrator>:<password> http://<host>:<port> /nodes/self"

**Comment by bentonam** [comment]
@accelide i'm going to close this issue as it is resolved, your latest request has it's own issue #76
