### ISSUE TITLE
Grafana Performance Dashboard `bucket_` Query Issues 

### ISSUE THREAD

**Issue by amfrye777** [couchbaselabs/cbprometheus_python#87]
The Grafana Performance Dashboard has references to `bucket_` metrics that do not exist. I believe most of these should be `data_`  or `index_`

![image](https://user-images.githubusercontent.com/19143491/89219091-cb3efb80-d594-11ea-957d-ca53cc7cbb34.png)

**Comment by bentonam** [comment]
This has been resolved, please look at the latest releases of the dashboards
